fast_localization:
  ros__parameters:
    lidar_topic: /sensors/lidar/points
    imu_topic: /sensors/imu
    odometry_topic: /fast_localization/odometry
    registered_points_topic: /fast_localization/cloud
    registered_body_points_topic: /fast_localization/cloud_body
    global_map_topic: /fast_localization/global_map
    path_topic: /fast_localization/path
    status_topic: /fast_localization/status
    map_frame_id: map
    body_frame_id: mid360_link
    time_sync_en: false
    time_offset_lidar_to_imu: 0.0
    lidar_type: 1
    scan_line: 4
    scan_rate: 10
    timestamp_unit: 3
    blind: 0.5
    point_filter_num: 3
    feature_extract_enable: false
    max_iteration: 3
    filter_size_corner: 0.5
    filter_size_surf: 0.5
    filter_size_map: 0.5
    cube_side_length: 1000.0
    det_range: 100.0
    fov_degree: 360.0
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    extrinsic_est_en: false
    extrinsic_t: [0.0, 0.0, 0.0]
    extrinsic_r: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
    path_en: true
    scan_publish_en: true
    dense_publish_en: true
    scan_bodyframe_pub_en: true
    runtime_pos_log_enable: false
    pcd_save_en: false
    pcd_save_interval: -1
